
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace kursMinin
{

using System;
    using System.Collections.Generic;
    
public partial class UserManService
{

    public int id { get; set; }

    public int Serviceid { get; set; }

    public int Usermanid { get; set; }

}

}
