
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace kursMinin
{

using System;
    using System.Collections.Generic;
    
public partial class Zakazy
{

    public int id { get; set; }

    public Nullable<int> Userid { get; set; }

    public string OrderTime { get; set; }

    public Nullable<int> Number { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<System.DateTime> Data { get; set; }



    public virtual Userman Userman { get; set; }

}

}
